#!/bin/bash
#--------------------------------------------------------
#   Don't remove this section for credits
#   Don't rename this file
#--------------------------------------------------------
#   This script is used to install Xderm Mini GUI custom theme
#   Installation script by helmiau a.k.a Helmi Amirudin
#   my profile page https://me.helmiau.my.id
#   my github https://github.com/helmiau
#--------------------------------------------------------
#   Theme Name  : Your Theme Name
#   Created by  : Ardi Setiawan
#   Contact     : https://www.facebook.com/ardi.o.setia
#   GitHub Link : https://github.com/squarepants96/xderm-mini-theme
#--------------------------------------------------------

#-- Warna Teks Installer
RED='\033[0;31m' # Merah
GRE='\033[1;32m' # Hijau Muda
BLU='\033[1;34m' # Biru Muda
YEL='\033[1;33m' # Kuning
NOR='\033[0;37m' # Abu Abu Normal


#-- Theme Info (you can edit these lines below)
#--------------------------------------------------------
# Add your theme name below, and place it between double quotes
	THEMENAME="Admin LTE"
#--------------------------------------------------------
# Add your name below, and place it between double quotes
	CREATOR="Ardi Setiawan"
#--------------------------------------------------------
# Add your github username below, and place it between double quotes
	GITUSER="squarepants96"
#--------------------------------------------------------
# Add your theme repository name below, and place it beteen double quotes
	GITREPO="xdrtheme-adminlte" 
#--------------------------------------------------------
# Add your used repository branch below, and place it between double quotes
	GITBRANCH="main"
#--------------------------------------------------------
#-- Theme Info End

#-- Uneditable Info for script checking purpose
INSTALLERNAME="$(basename "$0")"
CHECKNET="http://github.com/$GITUSER/$GITREPO"
URLTHEME="$CHECKNET/$GITBRANCH"
GITURLTHEME="git://github.com/$GITUSER/$GITREPO.git"
XDERMPATH="/www/xderm"
XDERMPATHBAK="/www/xdermbak"
THEMEINFO="/www/xderm/$GITREPO"
XDERMPATHINFO=$(if [ -d $XDERMPATH ]; then echo -e "${GRE}Available"; else echo -e "${RED}Unavailable"; fi)
XDERMPATHBAKINFO=$(if [ -d $XDERMPATHBAK ]; then echo -e "${GRE}Available"; else echo -e "${RED}Unavailable"; fi)
INSTALLSTAT=$(if [ -e $THEMEINFO ]; then echo -e "${GRE}Installed"; else echo -e "${RED}Not Installed"; fi)
USERNOW=$(grep user /root/auth.txt | sed 's/.*user=//')
PASSNOW=$(grep passwd /root/auth.txt | sed 's/.*passwd=//')
SCRIPTVER="1.0"

#-- Installer Scripts
echo -e "${NOR}==========================================="
echo -e "  ${YEL}Xderm Mini Theme Installer v$SCRIPTVER by helmiau${NOR}" #Do not remove this
echo "==========================================="
echo -e "  ${GRE}Theme Name     : $THEMENAME"
echo -e "  ${GRE}Theme Creator  : $CREATOR"
echo -e "  ${GRE}Theme Link     : github.com/$GITUSER/$GITREPO${NOR}"
echo -e "  ${GRE}Installer Name : $INSTALLERNAME${NOR}"
echo "==========================================="
echo -e "  ${GRE}Install Status : $INSTALLSTAT"
echo -e "  ${GRE}Xderm Path     : $XDERMPATHINFO"
echo -e "  ${GRE}Xderm Backup   : $XDERMPATHBAKINFO${NOR}"
echo "==========================================="
echo -e "  ${BLU}Panel Username : $USERNOW"
echo -e "  ${YEL}Panel Password : $PASSNOW${NOR}"
echo "==========================================="
echo -e "               ${YEL}Command Lists${NOR}"
echo -e "===========================================${GRE}"
echo "  Install Git & Wget       = 1 / g / G"
echo "  Install Theme            = 2 / i / I"
echo "  Reinstall/Update Theme   = 3 / r / R"
echo "  Uninstall Theme          = 4 / ut / UT"
echo "  Change User & Pass Login = 5 / a / A"
echo "  Change Username Only     = 6 / u / U"
echo "  Change Password Only     = 7 / p / P"
echo "  Install Login Page       = 8 / lp / LP"
echo "  Remove Login Page        = 9 / rlp/ RLP"
echo -e "${NOR}==========================================="
echo -e "           ${YEL}Exit = type anything !${NOR}"
echo "==========================================="
echo ""
echo -n "   Enter Your Option : " 
read -r jawab
echo "==========================================="
if [[ $jawab == "g" || $jawab == "G"  || $jawab == "1" ]]; then
	clear
	echo "  Checking connections..."
	if wget -S --spider $CHECKNET 2>&1 | grep -q 'HTTP/1.1 200 OK'; then
		echo "  Internet connected..."
		echo "  Installing Git Package..."
		echo "  Checking up git package availability..."
		if [[ $(opkg list-installed git | grep -c git) = "1" ]]; then
			echo "  Git package already installed..."
			echo "  Leaving..."
		else
			echo "  git package is not installed, installing..."
			opkg update && opkg install git
			echo "  Done !."
		fi
	else
		echo "  No connection..."
		echo "  Leaving."
	fi
	echo "==========================================="
	clear
	./$INSTALLERNAME
elif [[ $jawab == "i" || $jawab == "I"  || $jawab == "2" ]]; then
	clear
	echo "  Checking connections..."
	if wget -S --spider $CHECKNET 2>&1 | grep -q 'HTTP/1.1 200 OK' ; then
		echo "  Internet connected..."
		echo "  Installing $THEMENAME..."
		echo "  Checking paths..."
		if [[ -d $XDERMPATH ]]; then
			echo "  $XDERMPATH is available..."
			echo "  Creating backup path..."
			mv $XDERMPATH $XDERMPATHBAK
			echo "  Backup created..."
			mkdir $XDERMPATH
			echo "  Cloning $GITURLTHEME ..."
			git clone --depth 1 $GITURLTHEME $XDERMPATH
			echo "  Clone created..."
			echo "  $THEMENAME by $CREATOR installed..."
			echo "  Restoring Configs..."
			if [[ -d $XDERMPATHBAK/config ]]; then
				cp -R $XDERMPATHBAK/config $XDERMPATH/config
				echo "  Configs Restored..."
			else
				echo "  Config folder is not available, skipping..."			
			fi
			if [[ -d $XDERMPATHBAK/config.txt ]]; then
				cp $XDERMPATHBAK/config.txt $XDERMPATH/config.txt
				echo "  Configs Restored..."
			else
				echo "  Config file is not available, skipping..."			
			fi
			echo "  Starting Xderm Mini..."
			echo Start > /www/xderm/log/st
			echo "  Xderm Mini Started..."
			echo "  Done ! Refresh Xderm Mini Page"
		else
			echo "  $XDERMPATHBAK or $XDERMPATH is not available..."
			mkdir $XDERMPATH
			echo "  Cloning $GITURLTHEME ..."
			git clone --depth $GITURLTHEME 1 $XDERMPATH
			echo "  Clone created..."
			echo "  $THEMENAME by $CREATOR installed..."
			echo "  Starting Xderm Mini..."
			echo Start > /www/xderm/log/st
			echo "  Xderm Mini Started..."
			echo "  Done ! Refresh Xderm Mini Page"
		fi
	else
		echo "  No internet connection..."
		echo "  Leaving."
	fi
	echo "==========================================="
	clear
	./$INSTALLERNAME
elif [[ $jawab == "r" || $jawab == "R"  || $jawab == "3" ]]; then
	clear
	echo "  Checking connections..."
	if wget -S --spider $CHECKNET 2>&1 | grep -q 'HTTP/1.1 200 OK'; then
		echo "  Internet connected..."
		echo "  Backing up configurations..."
		if [[ -d $XDERMPATH/config ]]; then
			mv $XDERMPATH/config $XDERMPATH/configbak
			echo "  Configs backed up..."
		else
			echo "  Config folder is not available, skipping..."			
		fi
		if [[ -d $XDERMPATH/config.txt ]]; then
			mv $XDERMPATH/config.txt $XDERMPATH/config.txt.bak
			echo "  Configs backed up..."
		else
			echo "  Config file is not available, skipping..."			
		fi
		echo "  Reinstalling / Updating $THEMENAME theme..."
		echo "  Checking paths..."
		if [[ -d $XDERMPATH ]]; then
			echo "  $XDERMPATH is available..."
			echo "  Creating backup path..."
			mv $XDERMPATH $XDERMPATHBAK
			echo "  Backup created..."
			mkdir $XDERMPATH
			echo "  Cloning $GITURLTHEME ..."
			git clone --depth 1 $GITURLTHEME $XDERMPATH
			echo "  Clone created..."
			echo "  $THEMENAME by $CREATOR installed..."
			echo "  Restoring Configs..."
			if [[ -d $XDERMPATHBAK/config ]]; then
				cp -R $XDERMPATHBAK/config $XDERMPATH/config
				echo "  Configs Restored..."
			else
				echo "  Config folder is not available, skipping..."			
			fi
			if [[ -d $XDERMPATHBAK/config.txt ]]; then
				cp $XDERMPATHBAK/config.txt $XDERMPATH/config.txt
				echo "  Configs Restored..."
			else
				echo "  Config file is not available, skipping..."			
			fi
			cp $XDERMPATHBAK/config $XDERMPATH/config
			cp $XDERMPATHBAK/config.txt $XDERMPATH/config.txt
			echo "  Configs Restored..."
			echo "  Starting Xderm Mini..."
			echo Start > /www/xderm/log/st
			echo "  Xderm Mini Started..."
			echo "  Done ! Refresh Xderm Mini Page"
		else
			echo "  $XDERMPATHBAK or $XDERMPATH is not available..."
			mkdir $XDERMPATH
			echo "  Cloning $GITURLTHEME ..."
			git clone --depth $GITURLTHEME 1 $XDERMPATH
			echo "  Clone created..."
			echo "  $THEMENAME by $CREATOR installed..."
			echo "  Starting Xderm Mini..."
			echo Start > /www/xderm/log/st
			echo "  Xderm Mini Started..."
			echo "  Done ! Refresh Xderm Mini Page"
		fi
	else
		echo "  No connection..."
		echo "  Leaving."
	fi
	echo "==========================================="
	clear
	./$INSTALLERNAME
elif [[ $jawab == "ut" || $jawab == "UT"  || $jawab == "4" ]]; then
	clear
	echo "  Uninstalling $THEMENAME..."
	echo "  Checking paths..."
	if [[ -f $THEMEINFO ]]; then
		echo "  $THEMEINFO is $INSTALLSTAT..."
		echo "  $XDERMPATH is $XDERMPATHINFO..."
		echo "  $XDERMPATHBAK is $XDERMPATHBAKINFO..."
		echo "  Restoring Configs..."
		cp $XDERMPATH/config $XDERMPATHBAK/config
		cp $XDERMPATH/config.txt $XDERMPATHBAK/config.txt
		echo "  Removing $THEMENAME inside $XDERMPATH..."
		rm -rf $XDERMPATH
		echo "  Restoring backup..."
		mv $XDERMPATHBAK $XDERMPATH
		echo "  Backup restored..."
		echo "  $THEMENAME by $CREATOR uninstalled..."
		echo "  Starting Xderm Mini..."
		echo Start > /www/xderm/log/st
		echo "  Xderm Mini Started..."
		echo "  Done ! Refresh Xderm Mini Page"
	else
		echo "  $XDERMPATH or $XDERMPATHBAK or $THEMEINFO is not available..."
		echo "  Leaving ..."
	fi
	echo "==========================================="
	clear
	./$INSTALLERNAME
elif [[ $jawab == "a" || $jawab == "A"  || $jawab == "5" ]]; then
	echo -n "  Enter New Username : " 
	read -r USERNEW
	echo "==========================================="
	echo -n "  Enter New Password : " 
	read -r PASSNEW
	echo -e "user=$USERNEW\npasswd=$PASSNEW" > /root/auth.txt
	echo "==========================================="
	clear
	./$INSTALLERNAME
elif [[ $jawab == "u" || $jawab == "U"  || $jawab == "6" ]]; then
	echo -n "  Enter New Username : " 
	read -r USERNEW
	echo -e "user=$USERNEW\npasswd=$PASSNOW" > /root/auth.txt
	echo "==========================================="
	clear
	./$INSTALLERNAME
elif [[ $jawab == "p" || $jawab == "P"  || $jawab == "7" ]]; then
	echo -n "  Enter New Password : "
	read -r PASSNEW
	echo -e "user=$USERNOW\npasswd=$PASSNEW" > /root/auth.txt
	echo "==========================================="
	clear
	./$INSTALLERNAME
elif [[ $jawab == "lp" || $jawab == "LP"  || $jawab == "8" ]]; then
	clear
	echo "==========================================="
	echo -e "     Xderm Mini Login Page Installer by helmiau "
	echo "==========================================="
	echo -e " "
	echo -e "Notes : "
	echo -e "- This script will install xderm-mini login page"
	echo -e "- Please clear all web history and cache after removal!"
	echo -e "- If bug occured, Open incognito tab"
	echo -e "- If bug still occured, Use other browser"
	echo -e ""
	echo -e " Process starting after 2 secs....."
	sleep 2
	echo -e " Install process started..."
	sleep 1
	echo -e ""

	echo -e " Finding login.php file..."
	nyari=$(find /www/xderm)
	if [[ $nyari == *"login.php.xdrtool"* ]]; then
		mv /www/xderm/login.php.xdrtool /www/xderm/login.php
		echo -e " login.php file installed !"
		sleep 1
	else
		echo -e " Install failed ! because login.php backup file is unavailable"
		echo -e " Try online installation"
		wget -O /www/xderm/login.php $URLTHEME/login.php -q
		sleep 1
	fi

	echo -e " Finding header.php file..."
	nyari=$(find /www/xderm)
	if [[ $nyari == *"header.php.xdrtool"* ]]; then
		mv /www/xderm/header.php.xdrtool /www/xderm/header.php
		echo -e " header.php file installed !"
		sleep 1
	else
		echo -e " Install failed ! because header.php backup file is unavailable"
		echo -e " Try online installation"
		wget -O /www/xderm/header.php $URLTHEME/header.php -q
		sleep 1
	fi

	echo "==========================================="
	echo -e " Install login page process finished..."
	echo "==========================================="
	clear
	./$INSTALLERNAME
elif [[ $jawab == "rlp" || $jawab == "RLP"  || $jawab == "9" ]]; then
	clear
	clear
	echo "==========================================="
	echo -e "     Xderm Mini Login Page Remover by helmiau "
	echo "==========================================="
	echo -e " "
	echo -e "Notes : "
	echo -e "- This script will remove xderm-mini login page"
	echo -e "- Please clear all web history and cache after removal!"
	echo -e "- If bug occured, Open incognito tab"
	echo -e "- If bug still occured, Use other browser"
	echo -e ""
	echo -e " Process starting after 2 secs....."
	sleep 2
	echo -e " Removal process started..."
	sleep 1
	echo -e ""

	echo -e " Finding login.php file..."
	nyari=$(find /www/xderm)
	if [[ $nyari == *"login.php"* ]]; then
		mv /www/xderm/login.php /www/xderm/login.php.xdrtool
		echo -e " login.php file deleted !"
		sleep 1
	else
		echo -e " Removal failed ! because login.php file is unavailable"
		sleep 1
	fi

	echo -e " Finding header.php file..."
	nyari=$(find /www/xderm)
	if [[ $nyari == *"header.php"* ]]; then
		mv /www/xderm/header.php /www/xderm/header.php.xdrtool
		echo -e " header.php file deleted !"
		sleep 1
	else
		echo -e " Removal failed ! because login.php file is unavailable"
		sleep 1
	fi

	echo "==========================================="
	echo -e " Removal login page process finished..."
	echo "==========================================="
	clear
	./$INSTALLERNAME
else
	echo "    Exiting program !"
	echo "==========================================="
	exit
fi

#
#   This script is used to install Xderm Mini GUI custom theme
#   Installation script by helmiau a.k.a Helmi Amirudin
#   my profile page https://me.helmiau.my.id
#   my github https://github.com/helmiau
#
