#!/bin/bash
#--------------------------------------------------------
#   This script is used to install Xderm Mini GUI custom theme
#   Installation script by helmiau a.k.a Helmi Amirudin
#   my profile page https://me.helmiau.my.id
#   my github https://github.com/helmiau
#--------------------------------------------------------
#   Theme Name  : Admin LTE
#   Created by  : Ardi Setiawan
#   Contact     : https://www.facebook.com/ardi.o.setia
#   GitHub Link : https://github.com/squarepants96/xderm-mini-theme
#--------------------------------------------------------

#-- Warna Teks Installer
RED='\033[0;31m' #Merah
GRE='\033[1;32m' #Hijau Muda
BLU='\033[1;34m' #Biru Muda
YEL='\033[1;33m' #Kuning
NOR='\033[0;37m' #Abu Abu Normal

#-- Theme Info
THEMENAME="Admin LTE"
CREATOR="Ardi Setiawan"

#-- Installer Info
URL="https://github.com/squarepants96/xdrtheme-adminlte/main"
GITURLTHEME="git://github.com/squarepants96/xdrtheme-adminlte.git"
XDERMPATH="/www/xderm"
XDERMPATHBAK="/www/xdermbak"
THEMEINFO="/www/xderm/xdrtheme-adminlte-ardi-setiawan"
XDERMPATHINFO=$(if [ -d $XDERMPATH ]; then echo -e "${GRE}Available"; else echo -e "${RED}Unavailable"; fi)
XDERMPATHBAKINFO=$(if [ -d $XDERMPATHBAK ]; then echo -e "${GRE}Available"; else echo -e "${RED}Unavailable"; fi)
INSTALLSTAT=$(if [ -e $THEMEINFO ]; then echo -e "${GRE}Installed"; else echo -e "${RED}Not Installed"; fi)
USERNOW=$(grep user /root/auth.txt | sed 's/.*user=//')
PASSNOW=$(grep passwd /root/auth.txt | sed 's/.*passwd=//')

#-- Installer Scripts
echo "==========================================="
echo -e "|  ${BLU}Xderm Mini Theme Installer ${YEL}by helmiau${NOR}  |"
echo "==========================================="
echo -e "  ${GRE}Theme Name        : ${BLU}$THEMENAME"
echo -e "  ${GRE}Theme Creator     : ${BLU}$CREATOR${NOR}"
echo "==========================================="
echo -e "  ${GRE}Install Status    : $INSTALLSTAT"
echo -e "  ${GRE}Xderm Path        : $XDERMPATHINFO"
echo -e "  ${GRE}Xderm Path Backup : $XDERMPATHBAKINFO${NOR}"
echo "==========================================="
echo -e "  ${BLU}Panel Username    : ${BLU}$USERNOW"
echo -e "  ${YEL}Panel Password    : ${YEL}$PASSNOW${NOR}"
echo "==========================================="
echo -e "|              ${YEL}Command Lists${NOR}              |"
echo -e "===========================================${GRE}"
echo "  Install Theme               = 1 / it / IT"
echo "  Uninstall Theme             = 2 / ut / UT"
echo "  Change Username & Password  = 3 / a / A"
echo "  Change Username Only        = 4 / u / U"
echo "  Change Password Only        = 5 / p / P"
echo "  Install Login Page          = 6 / lp / LP"
echo "  Remove Login Page           = 7 / rlp/ RLP"
echo -e "${NOR}==========================================="
echo "  Exit = type anything !"
echo "==========================================="
echo ""
echo -n "  Enter Your Option : " 
read -r jawab
echo "==========================================="
if [[ $jawab == "it" || $jawab == "IT"  || $jawab == "1" ]]; then
clear
echo "  Installing $THEMENAME..."
echo "  Checking paths..."
if [[ -d $XDERMPATH ]]; then
    echo "  $XDERMPATH is available..."
    echo "  Creating backup path..."
	mv $XDERMPATH $XDERMPATHBAK
    echo "  Backup created..."
    mkdir $XDERMPATH
    echo "  Cloning $GITURLTHEME ..."
	git clone --depth 1 $GITURLTHEME $XDERMPATH
    echo "  Clone created..."
    echo "  $THEMENAME by $CREATOR installed..."
    echo "  Restoring Configs..."
	cp $XDERMPATHBAK/config $XDERMPATH/config
	cp $XDERMPATHBAK/config.txt $XDERMPATH/config.txt
    echo "  Configs Restored..."
    echo "  Starting Xderm Mini..."
	echo Start > /www/xderm/log/st
    echo "  Xderm Mini Started..."
    echo "  Done ! Refresh Xderm Mini Page"
else
    echo "  $XDERMPATHBAK or $XDERMPATH is not available..."
	mkdir $XDERMPATH
    echo "  Cloning $GITURLTHEME ..."
	git clone --depth $GITURLTHEME 1 $XDERMPATH
    echo "  Clone created..."
    echo "  $THEMENAME by $CREATOR installed..."
    echo "  Starting Xderm Mini..."
	echo Start > /www/xderm/log/st
    echo "  Xderm Mini Started..."
    echo "  Done ! Refresh Xderm Mini Page"
fi
echo "==========================================="
clear
./installer-adminlte
echo "==========================================="
elif [[ $jawab == "ut" || $jawab == "UT"  || $jawab == "2" ]]; then
clear
echo "  Uninstalling $THEMENAME..."
echo "  Checking paths..."
if [[ -f $THEMEINFO ]]; then
    echo "  $THEMEINFO is $INSTALLSTAT..."
    echo "  $XDERMPATH is $XDERMPATHINFO..."
    echo "  $XDERMPATHBAK is $XDERMPATHBAKINFO..."
    echo "  Restoring Configs..."
	cp $XDERMPATH/config $XDERMPATHBAK/config
	cp $XDERMPATH/config.txt $XDERMPATHBAK/config.txt
    echo "  Removing $THEMENAME inside $XDERMPATH..."
	rm -rf $XDERMPATH
    echo "  Restoring backup..."
	mv $XDERMPATHBAK $XDERMPATH
    echo "  Backup restored..."
    echo "  $THEMENAME by $CREATOR uninstalled..."
    echo "  Starting Xderm Mini..."
	echo Start > /www/xderm/log/st
    echo "  Xderm Mini Started..."
    echo "  Done ! Refresh Xderm Mini Page"
else
    echo "  $XDERMPATH or $XDERMPATHBAK or $THEMEINFO is not available..."
    echo "  Leaving ..."
fi
echo "==========================================="
clear
./installer-adminlte
echo "==========================================="
elif [[ $jawab == "a" || $jawab == "A"  || $jawab == "3" ]]; then
echo -n "  Enter New Username : " 
read -r USERNEW
echo "==========================================="
echo -n "  Enter New Password : " 
read -r PASSNEW
echo -e "user=$USERNEW\npasswd=$PASSNEW" > /root/auth.txt
echo "==========================================="
clear
./installer-adminlte
elif [[ $jawab == "u" || $jawab == "U"  || $jawab == "4" ]]; then
echo -n "  Enter New Username : " 
read -r USERNEW
echo -e "user=$USERNEW\npasswd=$PASSNOW" > /root/auth.txt
echo "==========================================="
clear
./installer-adminlte
elif [[ $jawab == "p" || $jawab == "P"  || $jawab == "5" ]]; then
echo -n "  Enter New Password : "
read -r PASSNEW
echo -e "user=$USERNOW\npasswd=$PASSNEW" > /root/auth.txt
echo "==========================================="
clear
./installer-adminlte
elif [[ $jawab == "lp" || $jawab == "LP"  || $jawab == "6" ]]; then
clear
echo "==========================================="
echo -e "     Xderm Mini Login Page Installer by helmiau "
echo "==========================================="
echo -e " "
echo -e "Notes : "
echo -e "- This script will install xderm-mini login page"
echo -e "- Please clear all web history and cache after removal!"
echo -e "- If bug occured, Open incognito tab"
echo -e "- If bug still occured, Use other browser"
echo -e ""
echo -e " Process starting after 2 secs....."
sleep 2
echo -e " Install process started..."
sleep 1
echo -e ""

echo -e " Finding login.php file..."
nyari=$(find /www/xderm)
if [[ $nyari == *"login.php.xdrtool"* ]]; then
mv /www/xderm/login.php.xdrtool /www/xderm/login.php
echo -e " login.php file installed !"
sleep 1
else
echo -e " Install failed ! because login.php backup file is unavailable"
echo -e " Try online installation"
wget -O /www/xderm/login.php $URL/login.php -q
sleep 1
fi

echo -e " Finding header.php file..."
nyari=$(find /www/xderm)
if [[ $nyari == *"header.php.xdrtool"* ]]; then
mv /www/xderm/header.php.xdrtool /www/xderm/header.php
echo -e " header.php file installed !"
sleep 1
else
echo -e " Install failed ! because header.php backup file is unavailable"
echo -e " Try online installation"
wget -O /www/xderm/header.php $URL/header.php -q
sleep 1
fi

echo "==========================================="
echo -e " Install login page process finished..."
echo "==========================================="
clear
./installer-adminlte
elif [[ $jawab == "rlp" || $jawab == "RLP"  || $jawab == "7" ]]; then
clear
clear
echo "==========================================="
echo -e "     Xderm Mini Login Page Remover by helmiau "
echo "==========================================="
echo -e " "
echo -e "Notes : "
echo -e "- This script will remove xderm-mini login page"
echo -e "- Please clear all web history and cache after removal!"
echo -e "- If bug occured, Open incognito tab"
echo -e "- If bug still occured, Use other browser"
echo -e ""
echo -e " Process starting after 2 secs....."
sleep 2
echo -e " Removal process started..."
sleep 1
echo -e ""

echo -e " Finding login.php file..."
nyari=$(find /www/xderm)
if [[ $nyari == *"login.php"* ]]; then
mv /www/xderm/login.php /www/xderm/login.php.xdrtool
echo -e " login.php file deleted !"
sleep 1
else
echo -e " Removal failed ! because login.php file is unavailable"
sleep 1
fi

echo -e " Finding header.php file..."
nyari=$(find /www/xderm)
if [[ $nyari == *"header.php"* ]]; then
mv /www/xderm/header.php /www/xderm/header.php.xdrtool
echo -e " header.php file deleted !"
sleep 1
else
echo -e " Removal failed ! because login.php file is unavailable"
sleep 1
fi

echo "==========================================="
echo -e " Removal login page process finished..."
echo "==========================================="
clear
./installer-adminlte
else
echo " Exiting program !"
echo "==========================================="
exit
fi